/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SimpleCounter } from './SimpleCounter.js';
export type { SimpleProxy } from './SimpleProxy.js';
export * as factories from './factories/index.js';
export { SimpleCounter__factory } from './factories/SimpleCounter__factory.js';
export { SimpleProxy__factory } from './factories/SimpleProxy__factory.js';