/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface SimpleProxyInterface extends Interface {
    getFunction(nameOrSignature: "count" | "getImplementation" | "implementation" | "owner" | "upgrade"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ImplementationUpgraded" | "ProxyCallExecuted"): EventFragment;

    encodeFunctionData(functionFragment: 'count', values?: undefined): string;
encodeFunctionData(functionFragment: 'getImplementation', values?: undefined): string;
encodeFunctionData(functionFragment: 'implementation', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'upgrade', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'count', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getImplementation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'implementation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'upgrade', data: BytesLike): Result;
  }

  
    export namespace ImplementationUpgradedEvent {
      export type InputTuple = [oldImplementation: AddressLike, newImplementation: AddressLike];
      export type OutputTuple = [oldImplementation: string, newImplementation: string];
      export interface OutputObject {oldImplementation: string, newImplementation: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProxyCallExecutedEvent {
      export type InputTuple = [caller: AddressLike, data: BytesLike];
      export type OutputTuple = [caller: string, data: string];
      export interface OutputObject {caller: string, data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SimpleProxy extends BaseContract {
    
    connect(runner?: ContractRunner | null): SimpleProxy;
    waitForDeployment(): Promise<this>;

    interface: SimpleProxyInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    count: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getImplementation: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    implementation: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    upgrade: TypedContractMethod<
      [newImplementation: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'count'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getImplementation'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'implementation'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'upgrade'): TypedContractMethod<
      [newImplementation: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ImplementationUpgraded'): TypedContractEvent<ImplementationUpgradedEvent.InputTuple, ImplementationUpgradedEvent.OutputTuple, ImplementationUpgradedEvent.OutputObject>;
getEvent(key: 'ProxyCallExecuted'): TypedContractEvent<ProxyCallExecutedEvent.InputTuple, ProxyCallExecutedEvent.OutputTuple, ProxyCallExecutedEvent.OutputObject>;

    filters: {
      
      'ImplementationUpgraded(address,address)': TypedContractEvent<ImplementationUpgradedEvent.InputTuple, ImplementationUpgradedEvent.OutputTuple, ImplementationUpgradedEvent.OutputObject>;
      ImplementationUpgraded: TypedContractEvent<ImplementationUpgradedEvent.InputTuple, ImplementationUpgradedEvent.OutputTuple, ImplementationUpgradedEvent.OutputObject>;
    

      'ProxyCallExecuted(address,bytes)': TypedContractEvent<ProxyCallExecutedEvent.InputTuple, ProxyCallExecutedEvent.OutputTuple, ProxyCallExecutedEvent.OutputObject>;
      ProxyCallExecuted: TypedContractEvent<ProxyCallExecutedEvent.InputTuple, ProxyCallExecutedEvent.OutputTuple, ProxyCallExecutedEvent.OutputObject>;
    
    };
  }