/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface SimpleCounterInterface extends Interface {
    getFunction(nameOrSignature: "count" | "getCount" | "increment" | "incrementBy" | "owner" | "reset" | "setOwner"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CountIncremented" | "CountReset"): EventFragment;

    encodeFunctionData(functionFragment: 'count', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'increment', values?: undefined): string;
encodeFunctionData(functionFragment: 'incrementBy', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'reset', values?: undefined): string;
encodeFunctionData(functionFragment: 'setOwner', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'count', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'increment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'incrementBy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reset', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setOwner', data: BytesLike): Result;
  }

  
    export namespace CountIncrementedEvent {
      export type InputTuple = [newCount: BigNumberish, caller: AddressLike];
      export type OutputTuple = [newCount: bigint, caller: string];
      export interface OutputObject {newCount: bigint, caller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CountResetEvent {
      export type InputTuple = [by: AddressLike];
      export type OutputTuple = [by: string];
      export interface OutputObject {by: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SimpleCounter extends BaseContract {
    
    connect(runner?: ContractRunner | null): SimpleCounter;
    waitForDeployment(): Promise<this>;

    interface: SimpleCounterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    count: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    increment: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    incrementBy: TypedContractMethod<
      [value: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    reset: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setOwner: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'count'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'increment'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'incrementBy'): TypedContractMethod<
      [value: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'reset'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setOwner'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CountIncremented'): TypedContractEvent<CountIncrementedEvent.InputTuple, CountIncrementedEvent.OutputTuple, CountIncrementedEvent.OutputObject>;
getEvent(key: 'CountReset'): TypedContractEvent<CountResetEvent.InputTuple, CountResetEvent.OutputTuple, CountResetEvent.OutputObject>;

    filters: {
      
      'CountIncremented(uint256,address)': TypedContractEvent<CountIncrementedEvent.InputTuple, CountIncrementedEvent.OutputTuple, CountIncrementedEvent.OutputObject>;
      CountIncremented: TypedContractEvent<CountIncrementedEvent.InputTuple, CountIncrementedEvent.OutputTuple, CountIncrementedEvent.OutputObject>;
    

      'CountReset(address)': TypedContractEvent<CountResetEvent.InputTuple, CountResetEvent.OutputTuple, CountResetEvent.OutputObject>;
      CountReset: TypedContractEvent<CountResetEvent.InputTuple, CountResetEvent.OutputTuple, CountResetEvent.OutputObject>;
    
    };
  }