/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SimpleCounter__factory } from './SimpleCounter__factory.js';
export { SimpleProxy__factory } from './SimpleProxy__factory.js';